services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=501
      - PGID=20
      - TZ=Etc/UTC
      - SERVERURL=wireguard.example.com
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: "service:wireguard"
    environment:
      - PUID=501
      - PGID=20
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - ./config/transmission:/config
      - ./share:/share
    restart: unless-stopped

  transmission-proxy:
    image: alpine/socat
    container_name: transmission-proxy
    command: tcp-listen:9091,fork,reuseaddr tcp-connect:wireguard:9091
    ports:
      - "9091:9091"
    depends_on:
      - wireguard
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM=claim-nMSFhYzSR1BxDBzKtBkf
    ports:
      - 32400:32400
      - 8324:8324
      - 32469:32469
      - 1900:1900/udp
      - 32410-32414:32410-32414/udp
    volumes:
      - ./share/media:/media
      - ./share/downloads:/downloads
      - ./config/plex:/config
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    ports:
      - 8096:8096
      - 7359:7359/udp
    volumes:
      - ./config/jellyfin:/config
      - ./share/media:/media
      - ./share/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - ./share:/share
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    ports:
      - 8989:8989
    volumes:
      - ./config/sonarr:/config
      - ./share:/share
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    ports:
      - 9696:9696
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - ./config/overseerr:/config
      - ./share:/share
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    ports:
      - 6767:6767
    volumes:
      - ./config/bazarr:/config
      - ./share:/share
    restart: unless-stopped

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: "1000:1000"
    environment:
      - TZ=America/New_York
    ports:
      - 6246:6246
    volumes:
      - ./config/maintainerr/data:/opt/data
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    user: "1000:1000"
    environment:
      - TZ=America/New_York
      - UN_START_DELAY=1m
    volumes:
      - ./share:/share
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer:/data
    restart: unless-stopped